use_frameworks!

target 'LLBase_Example' do
  pod 'LLBase', :path => '../'

  target 'LLBase_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
